### ISSUE TITLE
Torrent delete failed

### ISSUE THREAD

**Issue by Nemcio** [taobataoma/meanTorrent#17]
Hi
I'm using Linux (Arch) and can not delete. Display error:
Torrent delete failed

**Comment by taobataoma** [comment]
hi,

this error i need you send debug console detail info to me.

**Comment by Nemcio** [comment]
I have an error:
`Error: ENOENT: no such file or directory, unlink './modules/torrents/client/uploads/aaa1.torrent'
    at Object.fs.unlinkSync (fs.js:1063:18)
    at exports.delete (/home/user/meanTorrent/modules/torrents/server/controllers/torrents.server.controller.js:1026:6)
    at Layer.handle [as handle_request] (/home/user/meanTorrent/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/user/meanTorrent/node_modules/express/lib/router/route.js:137:13)
    at next (/home/user/meanTorrent/node_modules/express/lib/router/route.js:131:14)
    at next (/home/user/meanTorrent/node_modules/express/lib/router/route.js:131:14)
    at /home/user/meanTorrent/modules/torrents/server/policies/torrents.server.policy.js:112:16
    at tryCatcher (/home/user/meanTorrent/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/user/meanTorrent/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/home/user/meanTorrent/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/user/meanTorrent/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/meanTorrent/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/user/meanTorrent/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/user/meanTorrent/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/user/meanTorrent/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:785:20)`

**Comment by taobataoma** [comment]
hi,
very thanks, i fixed a issues on download torrent.

when you install meanTorrent first time? 

maybe you should update the code to newest and run ‘npm install’ before start it.

where r u from? It`s time to work?

**Comment by Nemcio** [comment]
I will install and check. I'm from Poland. Today is a holiday. I started translating meanTorrent into Polish.

**Comment by taobataoma** [comment]
@Nemcio maybe already fixed, only a eslint warning. I updated everyday.
