### ISSUE TITLE
remote DB+credentials DB

### ISSUE THREAD

**Issue by xxx31fr** [taobataoma/meanTorrent#56]
Hello,

I'd install MongoDB on the same server than MeanTorrent.
I'd like to have 2 differents servers:
1 for MongoDB
1 for Application MeanTorrent

How to modify Application code to connect to a remote DB
and, Second Question, I'd like to secure the DB, How to modifiy the application code to use user/password to connect to the MongoDB database?

Thanks.

**Comment by xxx31fr** [comment]
I would like to connect to a mongodb remote, I install a mongodb, I setuped it as it needed, I tested to connect mongodb server and it's OK.
I modifiied "config/env/comm-variable.js" with the IP of remote MongoDB server, but I get this error:

`Could not connect to MongoDB!
{ MongoError: failed to connect to server [10.10.31.45:27017] on first connect [MongoError: connect ECONNREFUSED 10.10.31.45:27017]
    at Pool.<anonymous> (/home/nody/meanTorrent/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at Pool.emit (events.js:180:13)
    at Connection.<anonymous> (/home/nody/meanTorrent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Socket.<anonymous> (/home/nody/meanTorrent/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:189:49)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
  name: 'MongoError',
  message: 'failed to connect to server [10.10.31.45:27017] on first connect [MongoError: connect ECONNREFUSED 10.10.31.45:27017]' }`


Can you, please, help me?

Thanks.

**Comment by taobataoma** [comment]
@xxx31fr Witch version of mongodb are you installed? looks problem is on mongodb.

**Comment by xxx31fr** [comment]
this is the last version mongodb

**Comment by xxx31fr** [comment]
can it be possible to change Mongodb with MySQL?
If yes, can you, please, details me how to use MySQL instead MongoDB?

Thank you so much for your help.

**Comment by taobataoma** [comment]
@xxx31fr meanTorrent don`t support Mysql, that need a lot of work should to do, and include many codes need to change. so meanTorrent only support mongoDB.

**Comment by wxpiero** [comment]
same error code here,I'm using AWS's mean eviroment snapshot,really frustrated
