### ISSUE TITLE
Heroku Error

### ISSUE THREAD

**Issue by mitsu375** [taobataoma/meanTorrent#61]
Apparently it builds fine in Heroku, but when I go to start I get the following error:

`2018-04-30T01:49:32.579547+00:00 heroku[web.1]: Starting process with command 'npm start'
2018-04-30T01:49:35.307770+00:00 app[web.1]: 
2018-04-30T01:49:35.307830+00:00 app[web.1]: > meanTorrent@0.1.0 start /app
2018-04-30T01:49:35.307832+00:00 app[web.1]: > gulp
2018-04-30T01:49:35.307834+00:00 app[web.1]: 
2018-04-30T01:49:36.336847+00:00 app[web.1]: internal/modules/cjs/loader.js:573
2018-04-30T01:49:36.336894+00:00 app[web.1]:     throw err;
2018-04-30T01:49:36.336896+00:00 app[web.1]:     ^
2018-04-30T01:49:36.336898+00:00 app[web.1]: 
2018-04-30T01:49:36.336900+00:00 app[web.1]: Error: Cannot find module 'semver'
2018-04-30T01:49:36.336902+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
2018-04-30T01:49:36.336904+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:497:25)
2018-04-30T01:49:36.336905+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:626:17)
2018-04-30T01:49:36.336907+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:20:18)
2018-04-30T01:49:36.336908+00:00 app[web.1]:     at Object.<anonymous> (/app/gulpfile.js:25:12)
2018-04-30T01:49:36.336910+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:678:30)
2018-04-30T01:49:36.336912+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
2018-04-30T01:49:36.336913+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:589:32)
2018-04-30T01:49:36.336915+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
2018-04-30T01:49:36.336917+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:520:3)
2018-04-30T01:49:36.349331+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2018-04-30T01:49:36.349940+00:00 app[web.1]: npm ERR! errno 1
2018-04-30T01:49:36.351743+00:00 app[web.1]: npm ERR! meanTorrent@0.1.0 start: `gulp`
2018-04-30T01:49:36.351999+00:00 app[web.1]: npm ERR! Exit status 1
2018-04-30T01:49:36.352375+00:00 app[web.1]: npm ERR! 
2018-04-30T01:49:36.352641+00:00 app[web.1]: npm ERR! Failed at the meanTorrent@0.1.0 start script.
2018-04-30T01:49:36.352889+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-04-30T01:49:36.394522+00:00 app[web.1]: 
2018-04-30T01:49:36.394764+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2018-04-30T01:49:36.394934+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2018-04-30T01_49_36_354Z-debug.log
2018-04-30T01:48:30.675715+00:00 heroku[web.1]: State changed from starting to crashed`

**Comment by din1369** [comment]
hi, im having the same error. do you able to fix it?
