### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Wralui** [taobataoma/meanTorrent#76]
hi, I followed all the instruction but I have mongodb problem that cant connect to db and DeprecationWarning
Info : Node 10, Mongo 4, bower 1.8
```
$  npm start

 meanTorrent@0.1.0 start D:\Access\meanTorrent
 gulp

[20:34:22] Using gulpfile D:\Access\meanTorrent\gulpfile.js
[20:34:22] Starting 'default'...
[20:34:22] Starting 'env:dev'...
[20:34:22] Finished 'env:dev' after 140 μs
[20:34:22] Starting 'copyLocalEnvConfig'...
[20:34:22] Starting 'makeUploadsDir'...
[20:34:22] Finished 'makeUploadsDir' after 562 μs
[20:34:22] Finished 'copyLocalEnvConfig' after 6.57 ms
[20:34:22] Starting 'lint'...
[20:34:22] Starting 'less'...
[20:34:24] Finished 'less' after 1.43 s
[20:34:24] Starting 'sass'...
[20:34:24] Finished 'sass' after 32 ms
[20:34:24] Starting 'csslint'...
[20:34:24] Starting 'eslint'...
[20:34:26] Finished 'csslint' after 1.82 s
[20:34:32] Finished 'eslint' after 7.82 s
[20:34:32] Finished 'lint' after 9.32 s
[20:34:32] Starting 'nodemon'...
[20:34:32] Finished 'nodemon' after 89 ms
[20:34:32] Starting 'watch'...
[20:34:32] Finished 'watch' after 528 ms
[20:34:32] Finished 'default' after 9.95 s
[20:34:32] [nodemon] 1.18.3
[20:34:32] [nodemon] to restart at any time, enter `rs`
[20:34:32] [nodemon] watching: modules/*/server/views/*.html server.js config/**/*.js modules/*/server/**/*.js modules/*/server/config/*.js
[20:34:32] [nodemon] watching extensions: js,html
[20:34:32] [nodemon] starting `node --inspect server.js`
[20:34:32] [nodemon] spawning
[20:34:32] [nodemon] child pid: 4040
Debugger listening on ws://127.0.0.1:9229/bd06708f-d3e5-4084-b2dd-52a19b844610
For help, see: https://nodejs.org/en/docs/inspector


[20:34:33] [nodemon] watching 777 files
(node:6536) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Could not connect to MongoDB!
{ Error: Cannot find module 'sharp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Access\meanTorrent\modules\torrents\server\controllers\torrents.server.controller.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Access\meanTorrent\modules\torrents\server\routes\torrents.server.routes.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at D:\Access\meanTorrent\config\lib\express.js:201:5
    at Array.forEach (<anonymous>) code: 'MODULE_NOT_FOUND' }
```

**Comment by Wralui** [comment]
problem solved, I used `yarn add sharp` instead of  `npm install -g sharp` I dont know why he didnt want to install in `node_module` repertory...
