### ISSUE TITLE
Error during Install

### ISSUE THREAD

**Issue by vr0** [taobataoma/meanTorrent#8]
```
Error: meanTorrent@0.1.0 prepublish: `npm run snyk-protect`
verbose stack Exit status 1
verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
verbose stack     at emitTwo (events.js:106:13)
verbose stack     at EventEmitter.emit (events.js:191:7)
verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
verbose stack     at emitTwo (events.js:106:13)
verbose stack     at ChildProcess.emit (events.js:191:7)
verbose stack     at maybeClose (internal/child_process.js:891:16)
erbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
verbose pkgid meanTorrent@0.1.0
```

```
> meanTorrent@0.1.0 snyk-protect /usr/home/mean/wednesday
> snyk protect

The patch against "node_modules/mocha/node_modules/ms" (npm:ms:20170412) failed.
The patch against "node_modules/socket.io-adapter/node_modules/ms" (npm:ms:20170412) failed.
Please email support@snyk.io if this problem persists.


npm ERR! FreeBSD 11.1-RELEASE
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "snyk-protect"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! meanTorrent@0.1.0 snyk-protect: `snyk protect`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanTorrent@0.1.0 snyk-protect script 'snyk protect'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meanTorrent package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     snyk protect
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meanTorrent
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meanTorrent
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/mean/wednesday/npm-debug.log
```

Kind regards,
vr0

**Comment by taobataoma** [comment]
@vr0 I've never seen this error. Are you sure your Node environment is all ok?

**Comment by vr0** [comment]
It sames that you must run the whole install as root user. 
So the issue/error message is gone.

**Comment by taobataoma** [comment]
@vr0 It may seem strange, but it's always good to have a problem solved, thanks!
